import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { readFile } from 'node:fs/promises';
import fixture from '../../fixtures/unit-1a/curriculum.json' with { type: 'json' };
import { newLearner, generateSession, recordAnswer, completeSession } from '../../app/engine.js';
import { readWorkspace as workspace } from './profile-db.js';
const file = (document,name='lesson.json') => ({name,mimeType:'application/json',buffer:Buffer.from(JSON.stringify(document))});
const library = page => page.locator('[data-view="library"]:visible').first().click();
const choose = (page,document,name) => page.locator('[data-import-file]').setInputFiles(file(document,name));

test('file preview preserves current answers and paused round, escapes text, exports current backup, and only applies explicitly',async({page})=>{
  await page.goto('/lernen.html');
  await page.locator('[data-action="start-learn"]').first().click();
  await page.locator('[data-draft-text]').fill('a deliberate mistake');
  await page.locator('[data-action="submit"]').click();
  await expect(page.locator('[data-action="next"]')).toBeEnabled();
  await page.locator('[data-action="exit"]').click();
  const original=await workspace(page);
  const incoming=structuredClone(fixture);
  incoming.curriculum.id='new-school-material';
  incoming.curriculum.title='<img src=x onerror=window.previewInjected=true> School material';
  incoming.curriculum.sources[0].notes='<script>window.previewInjected=true</script>';
  await library(page);
  await choose(page,incoming,'Eltern-Material.json');
  await expect(page.locator('[data-action="confirm-import"]')).toBeVisible();
  await expect(page.getByText('Datei: Eltern-Material.json',{exact:true})).toBeVisible();
  expect(await workspace(page)).toEqual(original);
  await expect(page.getByText(incoming.curriculum.title,{exact:true}).first()).toBeVisible();
  expect(await page.evaluate(()=>Boolean(window.previewInjected))).toBe(false);
  expect(await page.locator('#main img, #main script').count()).toBe(0);
  expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);
  await page.screenshot({path:'experiment/evidence/milestone3-import-desktop.png',fullPage:true});
  const downloaded=page.waitForEvent('download');
  await page.locator('[data-action="export-backup"]').click();
  const backup=JSON.parse(await readFile(await (await downloaded).path(),'utf8'));
  expect(backup.curriculum).toEqual(original.curriculum);
  expect(backup.learner).toEqual(original.learner);
  await expect(page.locator('[data-action="export-backup"]')).toBeFocused();
  await page.locator('[data-action="cancel-import"]').focus();
  await page.keyboard.press('Enter');
  expect(await workspace(page)).toEqual(original);
  await page.reload();
  await page.locator('[data-action="start-learn"]').first().click();
  await expect(page.locator('[data-action="next"]')).toBeEnabled();
  await page.locator('[data-action="exit"]').click();
  await library(page);await choose(page,incoming);
  await page.locator('[data-action="confirm-import"]').click();
  await expect(page.getByText(/Dein Lernstoff ist bereit/)).toBeVisible();
  await page.reload();
  const changed=await workspace(page);
  expect(changed.curriculum).toEqual(incoming.curriculum);
  expect(changed.learner.answerRecords).toEqual([]);
  expect(changed.session).toBe(null);
  expect(changed).not.toHaveProperty('pendingImport');
});

test('backup preview retries an aborted transaction, restores exact outcomes, and example switching also requires preview',async({page})=>{
  const course=structuredClone(fixture.curriculum);course.id='another-course';course.title='My school course';
  let learner=newLearner(course);
  const session=generateSession(course,learner,{conceptIds:['u1a.vocab.beach'],seed:'backup',now:'2026-09-10T12:00:00.000Z'});
  for(const exercise of session.exercises) learner=recordAnswer(learner,exercise,{correct:true,selfCheck:false,sessionId:session.id,answerId:`${session.id}:${exercise.id}`,curriculumId:course.id,curriculumVersion:course.version},{now:'2026-09-10T12:00:00.000Z'});
  learner=completeSession(learner,session);
  const backup={schemaVersion:'1.0',kind:'backup',curriculum:course,learner};
  await page.goto('/lernen.html');await library(page);
  const original=await workspace(page);
  await choose(page,backup,'Sicherung.json');
  await page.evaluate(()=>{window.realPut=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args){const request=window.realPut.apply(this,args);this.transaction.abort();return request;};});
  await page.locator('[data-action="confirm-import"]').click();
  await expect(page.getByText(/Speichern (wurde abgebrochen|fehlgeschlagen)/)).toBeVisible();
  expect(await workspace(page)).toEqual(original);
  await expect(page.locator('[data-action="confirm-import"]')).toBeEnabled();
  await page.evaluate(()=>{IDBObjectStore.prototype.put=window.realPut;});
  await page.locator('[data-action="confirm-import"]').click();
  await expect(page.getByText(/Sicherung wurde wiederhergestellt/)).toBeVisible();
  expect((await workspace(page)).learner).toEqual(learner);
  await page.reload();await library(page);
  await page.locator('[data-action="load-example"]').click();
  await expect(page.locator('[data-action="confirm-import"]')).toBeVisible();
  expect((await workspace(page)).learner).toEqual(learner);
  await page.locator('[data-action="cancel-import"]').click();
  await page.locator('[data-action="load-example"]').click();
  await page.locator('[data-action="confirm-import"]').click();
  await expect(page.getByText(/Dein Lernbuch ist schon da/)).toBeVisible();
  expect((await workspace(page)).curriculum.id).toBe(fixture.curriculum.id);
});

test('slow file reads serialize navigation and imports; readiness warnings and mobile preview remain usable',async({page,context})=>{
  await page.goto('/lernen.html');await library(page);
  const original=await workspace(page);
  await page.evaluate(()=>{
    window.readCount=0;
    const realText=File.prototype.text;
    File.prototype.text=async function(){window.readCount++;const text=await realText.call(this);return new Promise(resolve=>{window.finishRead=()=>resolve(text);});};
  });
  const blocked=structuredClone(fixture);
  blocked.curriculum.version='2.0'; // A changed prerequisite graph is a new curriculum revision.
  const writing=blocked.curriculum.concepts.find(c=>c.kind==='writing-skill');
  // Acyclic concept graph, but a self-check cannot unlock this prerequisite.
  writing.dependsOn=[];
  blocked.curriculum.concepts.find(c=>c.id==='u1a.vocab.beach').dependsOn=[writing.id];
  await choose(page,blocked);
  await expect(page.getByText(/Die Datei wird auf diesem Gerät geprüft/)).toBeVisible();
  await expect(page.locator('[data-import-file]')).toBeDisabled();
  await expect(page.locator('[data-action="navigate"]:visible').first()).toBeDisabled();
  await page.locator('[data-import-file]').dispatchEvent('change');
  expect(await page.evaluate(()=>window.readCount)).toBe(1);
  expect(await workspace(page)).toEqual(original);
  await page.waitForFunction(()=>Boolean(window.finishRead));
  await page.evaluate(()=>window.finishRead());
  await expect(page.locator('[data-action="confirm-import"]')).toBeVisible();
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await expect(page.getByText(/nicht erreichbar|nicht freischaltbar|nicht freigeschaltet/i).first()).toBeVisible();
  expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);
  await page.screenshot({path:'experiment/evidence/milestone3-import-mobile.png',fullPage:true});
  await page.setViewportSize({width:320,height:740});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.locator('[data-action="confirm-import"]').scrollIntoViewIfNeeded();
  await page.screenshot({path:'experiment/evidence/milestone3-import-phone-actions.png'});
  await page.locator('[data-action="cancel-import"]').click();
  const second=await context.newPage();await second.goto('/lernen.html');await library(second);
  await expect(second.locator('[data-import-file]')).toBeDisabled();
  await second.close();
  expect(await workspace(page)).toEqual(original);
});

test('failed file reads release the busy guard and discarded previews never survive reload',async({page})=>{
  await page.goto('/lernen.html');await library(page);
  const original=await workspace(page);
  await page.evaluate(()=>{
    window.realFileText=File.prototype.text;
    File.prototype.text=async()=>{throw new Error('Die ausgewählte Datei konnte nicht gelesen werden.');};
  });
  await choose(page,fixture);
  await expect(page.getByText('Die ausgewählte Datei konnte nicht gelesen werden.')).toBeVisible();
  await expect(page.locator('[data-import-file]')).toBeEnabled();
  expect(await workspace(page)).toEqual(original);
  await page.evaluate(()=>{File.prototype.text=window.realFileText;});
  await choose(page,fixture);
  await expect(page.locator('[data-action="confirm-import"]')).toBeVisible();
  await page.locator('[data-view="library"]:visible').first().click();
  await expect(page.locator('[data-action="confirm-import"]')).toHaveCount(0);
  await choose(page,fixture);
  await page.reload();
  await expect(page.locator('[data-action="start-learn"]').first()).toBeEnabled();
  await expect(page.locator('[data-action="confirm-import"]')).toHaveCount(0);
  expect(await workspace(page)).toEqual(original);
});
