import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { readFile } from 'node:fs/promises';
import french from '../../fixtures/french-smoke/curriculum.json' with { type: 'json' };
import { readWorkspace as workspace } from './profile-db.js';

const library = page => page.locator('[data-view="library"]:visible').first().click();

test('mobile pasted JSON preserves drafts and current progress through errors, edit, cancel and failed acceptance', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/lernen.html');
  await page.locator('[data-action="start-learn"]').first().click();
  await page.locator('[data-draft-text]').fill('wrong');
  await page.locator('[data-action="submit"]').click();
  await expect(page.locator('[data-action="next"]')).toBeEnabled();
  await page.locator('[data-action="exit"]').click();
  const original = await workspace(page);
  await library(page);
  await page.getByRole('button', { name: 'Text einfügen', exact: true }).click();
  const field = page.getByLabel('Lernstoff oder Sicherung als JSON');
  await field.fill('{ incomplete');
  await page.getByRole('button', { name: 'Vorschau öffnen' }).click();
  await expect(page.locator('#import-text-error')).toBeVisible();
  await expect(field).toHaveValue('{ incomplete');
  await expect(field).toBeFocused();
  expect(await workspace(page)).toEqual(original);
  const incoming = structuredClone(french);
  incoming.curriculum.title = '<img src=x onerror=window.injected=true>';
  const text = '```json\n' + JSON.stringify(incoming) + '\n```';
  await field.fill(text);
  await page.screenshot({ path: 'experiment/evidence/paste-import-mobile.png', fullPage: true });
  await page.getByRole('button', { name: 'Vorschau öffnen' }).click();
  await expect(page.locator('#import-preview-title')).toBeVisible();
  await expect(page.getByText('Quelle: Eingefügtes JSON', { exact: true })).toBeVisible();
  await expect(page.getByText(incoming.curriculum.title, { exact: true }).first()).toBeVisible();
  expect(await page.locator('#main img, #main script').count()).toBe(0);
  expect(await workspace(page)).toEqual(original);
  await page.getByRole('button', { name: 'Text bearbeiten' }).click();
  await expect(field).toHaveValue(text);
  await page.getByRole('button', { name: 'Vorschau öffnen' }).click();
  await page.getByRole('button', { name: 'Abbrechen', exact: true }).click();
  expect(await workspace(page)).toEqual(original);
  await page.getByRole('button', { name: 'Text einfügen', exact: true }).click();
  await expect(field).toHaveValue(text);
  await field.fill(JSON.stringify(french));
  await page.getByRole('button', { name: 'Vorschau öffnen' }).click();
  await page.evaluate(() => {
    window.originalPut = IDBObjectStore.prototype.put;
    IDBObjectStore.prototype.put = function (...args) { const request = window.originalPut.apply(this, args); this.transaction.abort(); return request; };
  });
  await page.getByRole('button', { name: 'Import übernehmen' }).click();
  await expect(page.getByText(/Speichern (wurde abgebrochen|fehlgeschlagen)/)).toBeVisible();
  expect(await workspace(page)).toEqual(original);
  await page.evaluate(() => { IDBObjectStore.prototype.put = window.originalPut; });
  await page.getByRole('button', { name: 'Import übernehmen' }).click();
  await expect(page.getByText(/Dein Lernstoff ist bereit/)).toBeVisible();
  await page.reload();
  await library(page);
  const saved = await workspace(page);
  expect(saved.curriculum).toEqual(french.curriculum);
  expect(saved).not.toHaveProperty('importTextDraft');
  expect(saved).not.toHaveProperty('pendingImport');
  const downloaded = page.waitForEvent('download');
  await page.locator('[data-action="export-backup"]').click();
  const download = await downloaded;
  expect(download.suggestedFilename()).toBe('lernpfad-sicherung.json');
  expect(JSON.parse(await readFile(await download.path(), 'utf8')).curriculum).toEqual(french.curriculum);
  await page.getByRole('button', { name: 'Text einfügen', exact: true }).click();
  await expect(field).toHaveValue('');
});

test('scout assets and direct authoring-to-paste flow work offline, without clipboard read, on narrow screens', async ({ page, context }) => {
  await page.goto('/lernen.html');
  await expect(page.locator('[data-action="start-learn"]').first()).toBeEnabled();
  await page.waitForFunction(() => [...document.images].every(image => image.complete && image.naturalWidth > 0));
  await page.screenshot({ path: 'experiment/evidence/scout-home-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'experiment/evidence/scout-home-mobile.png', fullPage: true });
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
  await page.evaluate(() => navigator.serviceWorker.ready);
  await page.reload();
  await page.waitForFunction(() => Boolean(navigator.serviceWorker.controller));
  const cdp = await context.newCDPSession(page);
  await cdp.send('Network.clearBrowserCache');
  await cdp.detach();
  await context.setOffline(true);
  await page.reload();
  await page.waitForFunction(() => [...document.images].every(image => image.complete && image.naturalWidth > 0));
  await library(page);
  await page.locator('.scout-art--field-kit img').scrollIntoViewIfNeeded();
  await page.waitForFunction(() => [...document.images].every(image => image.complete && image.naturalWidth > 0));
  await page.screenshot({ path: 'experiment/evidence/scout-library-mobile.png', fullPage: true });
  await page.getByRole('button', { name: 'Anleitung & Prompt' }).click();
  expect(await page.locator('[data-authoring-prompt]').inputValue()).toContain('nicht nur als Download-Link');
  await page.getByRole('button', { name: 'Text einfügen', exact: true }).click();
  await page.setViewportSize({ width: 320, height: 740 });
  const field = page.getByLabel('Lernstoff oder Sicherung als JSON');
  await field.fill('```json\n' + JSON.stringify(french) + '\n```');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
  await page.getByRole('button', { name: 'Vorschau öffnen' }).focus();
  await page.keyboard.press('Enter');
  await page.getByRole('button', { name: 'Import übernehmen' }).click();
  await page.locator('[data-view="home"]:visible').first().click();
  await page.locator('[data-action="start-learn"]').first().click();
  await expect(page.locator('#exercise-title')).toBeVisible();
});
